sudo: false
language: node_js
node_js:       
 - '8'

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master # (PRs to master, master merges, master pushes)
    - next # consolidating branch for breaking changes - need to build PRs

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER

before_install:
  - openssl aes-256-cbc -K $encrypted_6319a4cbc767_key -iv $encrypted_6319a4cbc767_iv -in github_deploy_key.enc -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm install -g grunt-cli

before_script:
  - git diff --exit-code
  - yarn check

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
    yarn run build &&
    npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push --tags git@github.com:$TRAVIS_REPO_SLUG.git &&
    npm publish --tag $NPM_TAG

after_success:
  - npm run coveralls

notifications:
  slack:
    secure: ACnCq4lvEhY9YFErraIrKy6spRPy4z/+PdFg0Fd4I8WtFf+Bc5qkOr17m8+lb3in4SNGsPPk1eue6ZDHvBkGn190GQfWIqqqs6lXh5UgBB4e2boTKe5lMpTmme7FMNQuUgt69Xr2J2J8Mt2N0C8DWAm0yKPlPjN/2HUVzkHPnemOsYQDjJ0GJxLwYiL8NM1tgwFfOXloFMCQuQxHZvKPxdjBOS5PMkyOG/717j806bbED2yuT3PeZQEj8h3rPxSHJTmTOuP4CKZtnxv+4kf3YbHWNvRogpoizlUuUhwXO1xpNzH58T5sFgPIr353WJeBpvHeIe8F8ekuJYBJIbbRkA3eIrJemlJzOjMzuXtSEKAgolkbu0FWiZuJ/HTjeCJK4r56UzCzYDLMA316uXQ1Nlbk5hXhnkL08xWf5mtXWyXt2/4OUq1Tn8hpr9ZohulTj3B/lV3CV+rFzxeFyfTJi7JN3lmRkUIZRMv28Kh2aIn91UZqOHkhPY184HJOOPtU+JeJUXMZ1ltrnGDP1GBSJcXiLY8rK6mdcJrZPtonFB5MBrGNPKejuTuMFHqs9bY5Dtd3PVfRi4f7VThp0IUZt9qo3Us/9weboClQpRwkbsNogZHnu0w+bnOqLR/ZLVGx5P1XO1u3iO6zfinhFBatD1KsVNwTfJvv0NCy+gvyG6A=

