sudo: false
language: node_js
node_js:       
 - '8'

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master # (PRs to master, master merges, master pushes)
    - next # consolidating branch for breaking changes - need to build PRs

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - secure: "aFd+aaK09SIpfb8YhW7OrVA9Y+pWL7WxzfIcLRfPF9X4cfM3zP27bRsnTJrT2c+LwjSuGmcyVc/T6jxBuOATyb8GIEqz+Qj+RrPymoIBw/5QyDZ1VsBL68DyXAZsAtMUQ/n41IbddJeJnYkjZPHOHgTLSBxkcm/Wy2kgWQEg1bTrQylQkrWFbK4XVxv2qHhaBs2mvBWIt/388tyCB6huzflL+ZhYvEsquOom9HS2I/cvO0VNxho80tpkH/LL/4HCng0R5LbnPmWnSMnEJzvhzPTQgOOx3PwdVu94DhlB8uSZK4TyEaEsr/HwLgMyNo8g8FI4C98ko0/BHuylwQKtu7ymAm8DZyfPpimSwBieK2WnK4t//hSeq5Vs8hjYMxlZubTRTloAK7N8z8F2d2BujHGzjXrL/vVs6eQqvlKOHpjVbMBRcc1ltwqMh3XuGwLBjs93B0jIc6bByB0eJQAx0LwIGG3tnuNe4B9x9Ar7UohHuqzz2/JuNeqcUqpQ2aBdd+XqmK2rn3DklGkLIkCQF0ww2bNKoYylx4WFRI5DXYqH252P+o5oBKQ8++EaFWXV3T9NMqRh6/wPgz0OVTvmlRJGPQadbPqNdGQzo60vVmvfzpZbuh6yowxxtg56HPhI7xthzyQwr0HYJ4tvbSAzs51vmQQ2/9sgFVDqFz5x0FA="

before_install:
  - openssl aes-256-cbc -K $encrypted_6319a4cbc767_key -iv $encrypted_6319a4cbc767_iv -in '.travis/github_deploy_key.enc' -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
  - npm install -g grunt-cli

before_script:
  - git diff --exit-code
  - yarn check

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - $(npm bin)/set-up-ssh --key "$encrypted_6319a4cbc767_key" --iv "$encrypted_6319a4cbc767_iv" --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
    yarn run build &&
    npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push --tags git@github.com:$TRAVIS_REPO_SLUG.git &&
    npm publish --tag $NPM_TAG

after_success:
  - npm run coveralls

notifications:
  slack:
    secure: ACnCq4lvEhY9YFErraIrKy6spRPy4z/+PdFg0Fd4I8WtFf+Bc5qkOr17m8+lb3in4SNGsPPk1eue6ZDHvBkGn190GQfWIqqqs6lXh5UgBB4e2boTKe5lMpTmme7FMNQuUgt69Xr2J2J8Mt2N0C8DWAm0yKPlPjN/2HUVzkHPnemOsYQDjJ0GJxLwYiL8NM1tgwFfOXloFMCQuQxHZvKPxdjBOS5PMkyOG/717j806bbED2yuT3PeZQEj8h3rPxSHJTmTOuP4CKZtnxv+4kf3YbHWNvRogpoizlUuUhwXO1xpNzH58T5sFgPIr353WJeBpvHeIe8F8ekuJYBJIbbRkA3eIrJemlJzOjMzuXtSEKAgolkbu0FWiZuJ/HTjeCJK4r56UzCzYDLMA316uXQ1Nlbk5hXhnkL08xWf5mtXWyXt2/4OUq1Tn8hpr9ZohulTj3B/lV3CV+rFzxeFyfTJi7JN3lmRkUIZRMv28Kh2aIn91UZqOHkhPY184HJOOPtU+JeJUXMZ1ltrnGDP1GBSJcXiLY8rK6mdcJrZPtonFB5MBrGNPKejuTuMFHqs9bY5Dtd3PVfRi4f7VThp0IUZt9qo3Us/9weboClQpRwkbsNogZHnu0w+bnOqLR/ZLVGx5P1XO1u3iO6zfinhFBatD1KsVNwTfJvv0NCy+gvyG6A=

